name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [native-image-macos, native-image-linux, native-image-windows]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 for Scala
        uses: olafurpg/setup-scala@v10
      - name: Get version from git tag
        run: echo "::set-output name=PUBLISH_VERSION::$(git describe --abbrev=0 --tags|cut -c2-)"
        id: version-tag
      - name: Test and publish
        env:
          CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
          CLOUDSMITH_PASS: ${{ secrets.CLOUDSMITH_PASS }}
        run: sbt test publish
      - name: Download native images
        uses: actions/download-artifact@v2
        with:
          name: "native-image"
      - name: Push macos native image
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_PASS }}
          command: "push"
          format: "raw"
          owner: "lightbend"
          repo: "akkaserverless"
          file: "akkasls-codegen-js-x86_64-apple-darwin"
          name: "akkasls-codegen-js-x86_64-apple-darwin"
          version: ${{ steps.version-tag.outputs.PUBLISH_VERSION }}
      - name: Push linux native image
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_PASS }}
          command: "push"
          format: "raw"
          owner: "lightbend"
          repo: "akkaserverless"
          file: "akkasls-codegen-js-x86_64-unknown-linux-gnu"
          name: "akkasls-codegen-js-x86_64-unknown-linux-gnu"
          version: ${{ steps.version-tag.outputs.PUBLISH_VERSION }}
      - name: Push Windows native image
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_PASS }}
          command: "push"
          format: "raw"
          owner: "lightbend"
          repo: "akkaserverless"
          file: "akkasls-codegen-js-x86_64-pc-windows-gnu.exe"
          name: "akkasls-codegen-js-x86_64-pc-windows-gnu"
          version: ${{ steps.version-tag.outputs.PUBLISH_VERSION }}

  native-image-macos:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Rename native image
        run: mv "js-gen-cli/target/native-image/akkasls-codegen-js" "akkasls-codegen-js-x86_64-apple-darwin"
      - name: Upload native image
        uses: actions/upload-artifact@v2
        with:
          path: "akkasls-codegen-js-x86_64-apple-darwin"
          name: "native-image"

  native-image-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Rename native image
        run: mv "js-gen-cli/target/native-image/akkasls-codegen-js" "akkasls-codegen-js-x86_64-unknown-linux-gnu"
      - name: Upload native image
        uses: actions/upload-artifact@v2
        with:
          path: "akkasls-codegen-js-x86_64-unknown-linux-gnu"
          name: "native-image"

  native-image-windows:
    runs-on: windows-latest

    steps:
      - name: Configure git
        run: "git config --global core.autocrlf false"
        shell: bash
      - uses: actions/checkout@v2
      - name: Provide MSVC dev command prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Scala with GraalVM
        uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@
      - name: Test and build
        shell: bash
        run: sbt test akkasls-codegen-js-cli/nativeImage
      - name: Rename native image
        run: mv "js-gen-cli/target/native-image/akkasls-codegen-js.exe" "akkasls-codegen-js-x86_64-pc-windows-gnu.exe"
      - name: Upload native image
        uses: actions/upload-artifact@v2
        with:
          path: "akkasls-codegen-js-x86_64-pc-windows-gnu.exe"
          name: "native-image"
